### ISSUE TITLE
building HYPRE 2.11.1 with Visual Studio 2015: syntax error in math.h

### ISSUE THREAD

**Issue by janusw** [LLNL/hypre#14]
After having trouble compiling HYPRE with the old VS2005 (see issue #12), I though it would be a good idea to try a newer version of VS and found a way to test VS2015 on Windows 10.

Unfortunately this was not much more successful than my previous attempt. While v2.11.0 works well in Debug mode, 2.11.1 seems to have trouble with VS2015: I'm configuring with the cmake generator "Visual Studio 14 2015 Win64" and set HYPRE_SEQUENTIAL, in order to disable MPI for the start. Then I start the build in Debug mode (to avoid issue #7).

What happens is that I get an error when compiling dgssvx.c from HYPRE_superlu:
```
1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.10240.0\ucrt\math.h(454): error C2059: Syntaxfehler: "("
```

The referenced line in math.h is:
```
_Check_return_ int       __cdecl abs(_In_ int _X);
```

Sounds pretty mysterious to me. Any words of advice?

Thanks,
Janus

**Comment by janusw** [comment]
Searching the web, I found this ...

http://forums.codeguru.com/showthread.php?223113-Include-file-math-h-compiles-error!

... which suggests that any "#define abs" might be the cuplrit. 

I see several of those in the HYPRE code:
```
$ grep -r '#define abs' *
blas/f2c.h:#define abs(x) ((x) >= 0 ? (x) : -(x))
FEI_mv/DSuperLU/CBLAS/f2c.h:#define abs(x) ((x) >= 0 ? (x) : -(x))
FEI_mv/DSuperLU/CBLAS/superlu_f2c.h:#define abs(x) ((x) >= 0 ? (x) : -(x))
FEI_mv/DSuperLU/INSTALL/dlamch.c:#define abs(x) ((x) >= 0 ? (x) : -(x))
FEI_mv/DSuperLU/INSTALL/slamch.c:#define abs(x) ((x) >= 0 ? (x) : -(x))
FEI_mv/DSuperLU/SRC/dlamch.c:#define abs(x) ((x) >= 0 ? (x) : -(x))
FEI_mv/DSuperLU/SRC/slamch.c:#define abs(x) ((x) >= 0 ? (x) : -(x))
FEI_mv/SuperLU/SRC/dlamch.c:#define abs(x) ((x) >= 0 ? (x) : -(x))
FEI_mv/SuperLU/SRC/slamch.c:#define abs(x) ((x) >= 0 ? (x) : -(x))
lapack/f2c.h:#define abs(x) ((x) >= 0 ? (x) : -(x))
```

Cheers,
Janus

**Comment by janusw** [comment]
Trying the tags from github:
-  v2.11.0-1-g5aeeaec works
-  v2.11.0-44-g001722f fails


> ... which suggests that any "#define abs" might be the cuplrit.
>
> I see several of those in the HYPRE code:

... however all of them are already present in v2.11.0.

**Comment by janusw** [comment]
It seems that the problem is basically due to the ordering of #include statements. In particular the introduction of an `#include "math.h"` in hypre_lapack.h in v2.11.0-44 appears to be the primary troublemaker. In order to fix this, I guess one should follow the good old rule of including system headers (like math.h) before any project-specific headers.

Cheers,
Janus

**Comment by rfalgout** [comment]
VS 2015 issues were resolved in version 2.13.0
